---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
  labels:
    app: foo
  # annotations:
    # konghq.com/plugins: rate-limiting
spec:
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: foo